export const dynamic = 'force-dynamic';
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { SPORT_LABELS } from '@/lib/constants';
import { skillLabels, type CommunityProfile } from '@/lib/community';
import { Camera, ShieldCheck } from 'lucide-react';
import { AvatarUpload } from '@/components/avatar-upload';
import { ActionForm } from '@/components/action-form';
import { Field, fieldClass } from '@/components/form-field';
export const metadata = { title: 'Hồ sơ kết nối của tôi' };
export default async function Page() {
  const db = await createClient(); const { data: { user } } = await db.auth.getUser();
  if (!user) redirect('/dang-nhap?next=/ket-noi/ho-so');
  const [{ data, error }, { data: account }] = await Promise.all([db.rpc('get_community_profile',{ p_id: user.id }),db.from('profiles').select('full_name,phone,avatar_url').eq('id',user.id).maybeSingle()]);
  if (error) throw new Error('Không tải được hồ sơ kết nối.'); const p = data as CommunityProfile | null;
  return <main className="mx-auto max-w-5xl px-5 py-10 lg:py-14">
    <Link href="/ket-noi" className="inline-flex min-h-11 items-center text-sm font-semibold text-pitch">← Kết nối người chơi</Link>
    <header className="mb-8 mt-4"><p className="text-xs font-bold uppercase tracking-widest text-ink-secondary">Một lời chào trước khi ra sân</p><h1 className="mt-3 font-display text-3xl font-extrabold tracking-tight text-pitch sm:text-4xl">Hồ sơ kết nối của tôi</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-ink-secondary">Cho người chơi khác biết bạn thích môn gì, thường chơi ở đâu và cách liên hệ thuận tiện.</p></header>
    <div className="grid items-start gap-6 lg:grid-cols-[1fr_260px]">
      <section className="min-w-0 rounded-card border border-hairline bg-card p-5 sm:p-7"><div className="mb-6 border-b border-hairline pb-6"><div className="mb-5 flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-control bg-free-fill text-pitch"><Camera className="size-5" strokeWidth={1.5} aria-hidden="true" /></span><div><h2 className="font-display text-xl font-bold text-pitch">Một gương mặt, một lời chào</h2><p className="mt-1 text-xs leading-6 text-ink-secondary">Ảnh đại diện của bạn trên Sân Ngon.</p></div></div><AvatarUpload userId={user.id} name={p?.display_name ?? account?.full_name ?? 'Bạn'} avatar={account?.avatar_url ?? null} /></div><ActionForm endpoint="/api/community" label="Lưu hồ sơ kết nối">
        <div className="space-y-5"><h2 className="border-b border-hairline pb-4 font-display text-xl font-bold text-pitch">Bạn trên sân</h2><Field label="Tên hiển thị"><input className={fieldClass} name="display_name" autoComplete="name" defaultValue={p?.display_name ?? account?.full_name ?? ''} required minLength={2} maxLength={100} /></Field><Field label="Khu vực / vị trí"><input className={fieldClass} name="location" defaultValue={p?.location ?? ''} placeholder="Ví dụ: Cầu Giấy, Hà Nội" required minLength={2} maxLength={200} /></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Môn chơi"><select className={fieldClass} name="sport" defaultValue={p?.sport ?? 'badminton'}>{Object.entries(SPORT_LABELS).map(([k,v]) => <option key={k} value={k}>{v}</option>)}</select></Field><Field label="Trình độ"><select className={fieldClass} name="skill_level" defaultValue={p?.skill_level ?? 'beginner'}>{Object.entries(skillLabels).map(([k,v]) => <option key={k} value={k}>{v}</option>)}</select></Field></div><Field label="Khung giờ thường chơi"><input className={fieldClass} name="usual_play_times" defaultValue={p?.usual_play_times ?? ''} maxLength={300} placeholder="Ví dụ: Tối thứ 3, 5 sau 19h; sáng Chủ nhật" /></Field><Field label="Giới thiệu"><textarea className={fieldClass} name="bio" defaultValue={p?.bio ?? ''} maxLength={1000} rows={4} placeholder="Bạn thường chơi lúc nào? Thích giao lưu vui vẻ hay luyện tập thi đấu?" /></Field></div>
        <div className="space-y-5 pt-5"><h2 className="border-b border-hairline pb-4 font-display text-xl font-bold text-pitch">Cách liên hệ với bạn</h2><div className="grid gap-5 sm:grid-cols-2"><Field label="Số điện thoại liên hệ"><input className={fieldClass} name="phone" type="tel" autoComplete="tel" defaultValue={p?.phone ?? account?.phone ?? ''} required minLength={10} maxLength={25} /></Field><Field label="Số Zalo (tùy chọn)"><input className={fieldClass} name="zalo_phone" type="tel" defaultValue={p?.zalo_phone ?? ''} maxLength={25} /></Field></div><Field label="Trang Facebook (tùy chọn)"><input className={fieldClass} type="url" name="facebook_url" defaultValue={p?.facebook_url ?? ''} maxLength={300} placeholder="https://facebook.com/ten-cua-ban" /></Field></div>
        <fieldset className="space-y-3 rounded-control border border-hairline p-4"><legend className="px-2 text-sm font-semibold text-pitch">Kênh liên hệ muốn công khai</legend><p className="text-xs leading-6 text-ink-secondary">Chỉ các kênh bạn chọn mới hiện với người khác. Bạn có thể công khai hồ sơ mà vẫn ẩn toàn bộ thông tin liên hệ.</p>{[['show_phone','Điện thoại',p?.show_phone],['show_zalo','Zalo',p?.show_zalo],['show_facebook','Facebook',p?.show_facebook]].map(([name,label,checked]) => <label key={String(name)} className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" name={String(name)} defaultChecked={checked === true} className="size-5 accent-pitch" />{String(label)}</label>)}</fieldset><label className="flex items-start gap-3 rounded-control border border-strong bg-free-fill p-4 text-sm leading-7"><input className="mt-1.5 size-5 shrink-0 accent-pitch" type="checkbox" name="is_public" defaultChecked={p?.is_public ?? false} /><span>Tôi đồng ý công khai hồ sơ và các kênh liên hệ đã chọn trên mục Kết nối. <span className="block text-xs leading-6 text-ink-secondary">Mọi người, kể cả chưa đăng nhập, có thể xem. Bỏ chọn và lưu để ẩn hồ sơ bất cứ lúc nào.</span></span></label>
      </ActionForm></section>
      <aside className="rounded-card border border-strong bg-free-fill p-6 lg:sticky lg:top-24"><div className="mb-4 grid size-10 place-items-center rounded-control border border-strong bg-card text-pitch"><ShieldCheck className="size-5" strokeWidth={1.5} aria-hidden="true" /></div><p className="text-xs font-bold uppercase tracking-widest text-ink-secondary">Quyền hiển thị hồ sơ</p><p className="mt-3 font-display text-2xl font-bold text-pitch">{p?.is_public ? 'Đang công khai' : 'Chỉ mình bạn'}</p><p className="mt-3 text-sm leading-7 text-ink-secondary">{p?.is_public ? 'Người chơi có thể tìm thấy hồ sơ và liên hệ với bạn.' : 'Thông tin chưa xuất hiện trong danh sách người chơi. Bạn có thể lưu trước và công khai sau.'}</p>{p && <Link href={`/ket-noi/${user.id}`} className="mt-4 inline-flex min-h-11 items-center text-sm font-semibold text-pitch underline underline-offset-4">Xem hồ sơ của tôi ↗</Link>}<div className="mt-5 border-t border-strong pt-5"><p className="text-sm leading-7 text-ink-secondary">Đổi ảnh không tự công khai hồ sơ. Bạn quyết định thông tin và kênh liên hệ nào được hiển thị.</p><Link className="mt-2 inline-flex min-h-11 items-center text-sm font-semibold text-pitch underline underline-offset-4" href="/tai-khoan">Thông tin tài khoản ↗</Link></div></aside>
    </div>
  </main>;
}
