'use client';
import { useState } from 'react';
import { SPORT_LABELS } from '@/lib/constants';
import { Field, fieldClass } from './form-field';
export function TournamentFields({ courts, initial, owner = false }: { initial?: Record<string, string | number>; owner?: boolean; courts: { id: string; name: string; venue: string; address: string; sport: string }[] }) {
  const [sport, setSport] = useState(String(initial?.sport ?? courts[0]?.sport ?? Object.keys(SPORT_LABELS)[0]));
  const [courtId, setCourtId] = useState(String(initial?.court_id ?? ''));
  const court = courts.find(c => c.id === courtId && c.sport === sport);
  return <>
    <section id="thong-tin-giai" className="scroll-mt-6 space-y-5"><div className="border-b border-hairline pb-4"><p className="text-xs font-bold tracking-widest text-ink-secondary">01 / THÔNG TIN GIẢI</p><h2 className="mt-2 font-display text-2xl font-bold text-pitch">Bạn muốn tổ chức giải gì?</h2></div>
      <Field label="Tên giải"><input className={fieldClass} name="title" defaultValue={initial?.title} placeholder="Ví dụ: Cầu lông cuối tuần Cầu Giấy" required minLength={3} maxLength={150} /></Field>
      <div className="grid gap-5 sm:grid-cols-2"><Field label="Môn thi đấu"><select className={fieldClass} name="sport" value={sport} onChange={event => { setSport(event.target.value); setCourtId(''); }}>{Object.entries(SPORT_LABELS).map(([k,v]) => <option key={k} value={k}>{v}</option>)}</select></Field><Field label="Sân tổ chức"><select className={fieldClass} name="court_id" required={owner} value={court?.id ?? ''} onChange={event => setCourtId(event.target.value)}><option value="">{owner ? 'Chọn sân của bạn' : 'Nhờ admin bố trí sân'}</option>{courts.filter(c => c.sport === sport).map(c => <option key={c.id} value={c.id}>{c.venue} · {c.name}</option>)}</select></Field></div>
      {owner ? <Field label="Địa chỉ sân tổ chức"><input className={`${fieldClass} bg-sunk`} name="address" value={court?.address ?? ''} readOnly placeholder="Chọn sân để xem địa chỉ" /></Field> : <Field label="Địa chỉ / khu vực mong muốn"><input className={fieldClass} name="address" defaultValue={initial?.address} placeholder="Quận, địa chỉ sân hoặc khu vực thuận tiện" required minLength={5} maxLength={300} /></Field>}
      {owner && !courts.some(c => c.sport === sport) && <p role="status" className="text-sm leading-6 text-ink-secondary">Bạn chưa có sân đang hoạt động cho môn này. Chọn môn khác hoặc thêm sân trong phần quản lý.</p>}
      <p className="text-xs leading-6 text-ink-secondary">{owner ? 'Chỉ hiện sân đang hoạt động của bạn, đúng môn đã chọn. Giải được công khai ngay và dùng địa chỉ của sân. Kiểm tra kỹ lịch, lệ phí và thể lệ trước khi công khai.' : 'Admin sẽ bố trí sân và duyệt đề xuất. Bạn được quản lý danh sách tham gia sau khi giải được công khai.'}</p>
    </section>
    <section id="lich-giai" className="scroll-mt-6 space-y-5 pt-6"><div className="border-b border-hairline pb-4"><p className="text-xs font-bold tracking-widest text-ink-secondary">02 / LỊCH & QUY MÔ</p><h2 className="mt-2 font-display text-2xl font-bold text-pitch">Hẹn ngày ra sân</h2><p className="mt-2 text-sm text-ink-secondary">Tất cả thời gian là giờ Việt Nam. Chốt đăng ký trước hạn cọc, và chốt cọc trước khi giải bắt đầu.</p></div>
      <div className="grid gap-5 sm:grid-cols-2"><Field label="Bắt đầu (giờ Việt Nam)"><input className={fieldClass} type="datetime-local" name="starts_at" defaultValue={initial?.starts_at} required /></Field><Field label="Kết thúc (giờ Việt Nam)"><input className={fieldClass} type="datetime-local" name="ends_at" defaultValue={initial?.ends_at} required /></Field><Field label="Hạn nhận và duyệt đăng ký"><input className={fieldClass} type="datetime-local" name="registration_deadline" defaultValue={initial?.registration_deadline} required /></Field><Field label="Hạn đóng cọc cuối cùng"><input className={fieldClass} type="datetime-local" name="payment_deadline" defaultValue={initial?.payment_deadline} required /></Field><Field label="Thời gian đóng cọc sau duyệt (giờ)"><input className={fieldClass} type="number" name="payment_hold_hours" min={1} max={72} defaultValue={initial?.payment_hold_hours ?? 24} required /></Field><Field label="Số người / đội tối đa"><input className={fieldClass} type="number" name="capacity" defaultValue={initial?.capacity} min={2} max={1000} placeholder="Ví dụ: 16" required /></Field></div>
      <p className="text-xs leading-6 text-ink-secondary">Mỗi tài khoản đăng ký một suất. Ghi rõ một suất là một người hay một đội trong thể lệ.</p>
    </section>
    <section id="le-phi-giai" className="scroll-mt-6 space-y-5 pt-6"><div className="border-b border-hairline pb-4"><p className="text-xs font-bold tracking-widest text-ink-secondary">03 / LỆ PHÍ & THỂ LỆ</p><h2 className="mt-2 font-display text-2xl font-bold text-pitch">Rõ ràng trước khi tham gia</h2></div>
      <div className="grid gap-5 sm:grid-cols-2"><Field label="Lệ phí mỗi suất (đ)"><input className={fieldClass} type="number" name="entry_fee" min={0} max={100000000} defaultValue={initial?.entry_fee ?? 0} required /></Field><Field label="Cọc mỗi suất (đ)"><input className={fieldClass} type="number" name="deposit_amount" min={0} max={100000000} defaultValue={initial?.deposit_amount ?? 0} required /></Field></div>
      <p className="rounded-control bg-free-fill p-4 text-sm leading-7 text-pitch">Để 0 nếu miễn phí. Cọc là một phần của lệ phí, không được vượt tổng lệ phí. Người được duyệt mới chuyển cọc; phần còn lại nộp khi tham gia.</p>
      <Field label="Thể lệ, trình độ, quy mô và thông tin liên hệ"><textarea className={fieldClass} name="description" defaultValue={initial?.description} placeholder="Giải dành cho ai? Thi đấu cá nhân hay theo đội? Thể thức, lịch có mặt, dụng cụ cần mang và cách liên hệ ban tổ chức…" required minLength={10} maxLength={5000} rows={7} /></Field>
      <p className="text-xs leading-6 text-ink-secondary">Cọc được xác nhận tự động qua SePay vào tài khoản chủ sân. Người chơi hủy trước giờ bắt đầu ít nhất 24 giờ được hoàn 100% cọc; muộn hơn không hoàn cọc. Ban tổ chức hủy suất hoặc hủy giải luôn hoàn 100%. Chủ sân hoàn thủ công.</p>
    </section>
  </>;
}
