'use client';

import { useState } from 'react';
import { DISTRICTS, SPORT_LABELS, VENUE_STATUS_LABELS } from '@/lib/constants';

type PriceRule = { label: string | null; price_per_hour: number; start_time: string; end_time: string };
type Court = { id: string; name: string; sport: keyof typeof SPORT_LABELS; surface: string | null; is_indoor: boolean; slot_minutes: number; open_time: string | null; close_time: string | null; is_active: boolean; price_rules: PriceRule[] };
type Venue = { id: string; name: string; address: string; district: string; phone: string | null; description: string | null; open_time: string; close_time: string; deposit_pct: number; booking_horizon_days: number; status: keyof typeof VENUE_STATUS_LABELS; courts: Court[] };
type Props = { initialVenues: Venue[] };
type VenueDraft = { name: string; address: string; district: string; phone: string; description: string; deposit_pct: number; booking_horizon_days: number; open_time: string; close_time: string };
type CourtDraft = { venue_id?: string; name: string; sport: Court['sport']; surface: string; is_indoor: boolean; slot_minutes: number; open_time: string; close_time: string; is_active: boolean; price_per_hour: number };

const INPUT = 'h-11 w-full rounded-control border border-hairline bg-page px-3 text-sm outline-none focus:border-pitch focus:ring-2 focus:ring-strong';
const EMPTY_COURT: CourtDraft = { name: '', sport: 'football5', surface: '', is_indoor: false, slot_minutes: 60, open_time: '', close_time: '', is_active: true, price_per_hour: 250000 };

export function VenueManagement({ initialVenues }: Props) {
  const [venues, setVenues] = useState(initialVenues);
  const [editingVenue, setEditingVenue] = useState<string | null>(null);
  const [editingCourt, setEditingCourt] = useState<string | null>(null);
  const [addingCourt, setAddingCourt] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  function showError(text: string) { setError(text); setMessage(null); }
  function showMessage(text: string) { setMessage(text); setError(null); }
  async function request(url: string, method: 'PATCH' | 'POST' | 'DELETE', body?: unknown) {
    const response = await fetch(url, { method, headers: body ? { 'content-type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined });
    const result = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(result.error ?? 'Không lưu được.');
    return result;
  }
  async function saveVenue(id: string, draft: VenueDraft) {
    try { const result = await request(`/api/venues/${id}`, 'PATCH', { ...draft, deposit_pct: Number(draft.deposit_pct), booking_horizon_days: Number(draft.booking_horizon_days) }); setVenues((rows) => rows.map((v) => v.id === id ? { ...v, ...result.venue } : v)); setEditingVenue(null); showMessage('Đã lưu thông tin cụm sân.'); } catch (e) { showError((e as Error).message); }
  }
  async function deleteVenue(venue: Venue) {
    if (!window.confirm(`Xóa cụm sân “${venue.name}”? Chỉ xóa được khi chưa có đơn đặt.`)) return;
    try { await request(`/api/venues/${venue.id}`, 'DELETE'); setVenues((rows) => rows.filter((v) => v.id !== venue.id)); showMessage('Đã xóa cụm sân.'); } catch (e) { showError((e as Error).message); }
  }
  async function saveCourt(venueId: string, draft: CourtDraft, id?: string) {
    const body = { ...draft, venue_id: undefined, open_time: draft.open_time || null, close_time: draft.close_time || null, surface: draft.surface || null, price_per_hour: Number(draft.price_per_hour) };
    try {
      const result = await request(id ? `/api/courts/${id}` : '/api/courts', id ? 'PATCH' : 'POST', id ? body : { ...body, venue_id: venueId });
      setVenues((rows) => rows.map((v) => v.id !== venueId ? v : { ...v, courts: id ? v.courts.map((c) => c.id === id ? { ...c, ...result.court } : c) : [...v.courts, { ...result.court, price_rules: [{ price_per_hour: draft.price_per_hour, label: 'Giá chung', start_time: draft.open_time || v.open_time, end_time: draft.close_time || v.close_time }] }] }));
      setEditingCourt(null); setAddingCourt(null); showMessage(id ? 'Đã lưu sân con.' : 'Đã thêm sân con.');
    } catch (e) { showError((e as Error).message); }
  }
  async function deleteCourt(venueId: string, court: Court) {
    if (!window.confirm(`Xóa sân “${court.name}”? Nếu đã có đơn, hãy tắt sân thay vì xóa.`)) return;
    try { await request(`/api/courts/${court.id}`, 'DELETE'); setVenues((rows) => rows.map((v) => v.id === venueId ? { ...v, courts: v.courts.filter((c) => c.id !== court.id) } : v)); showMessage('Đã xóa sân con.'); } catch (e) { showError((e as Error).message); }
  }

  return <div className="space-y-6">{(message || error) && <p role={error ? 'alert' : 'status'} className={`rounded-card border px-4 py-3 text-sm ${error ? 'border-danger bg-[#FFF5F5] text-danger' : 'border-free-line bg-free-fill text-free-ink'}`}>{error ?? message}</p>}{venues.length === 0 ? <p className="rounded-card border border-dashed border-strong p-10 text-center text-sm text-ink-secondary">Bạn chưa có cụm sân nào.</p> : venues.map((venue) => <VenueCard key={venue.id} venue={venue} editing={editingVenue === venue.id} onEdit={() => setEditingVenue(venue.id)} onCancel={() => setEditingVenue(null)} onSave={(draft) => saveVenue(venue.id, draft)} onDelete={() => deleteVenue(venue)} addingCourt={addingCourt === venue.id} onAddCourt={() => { setAddingCourt(venue.id); setEditingCourt(null); }} onCancelCourt={() => setAddingCourt(null)} onSaveCourt={(draft) => saveCourt(venue.id, draft)} editingCourt={editingCourt} onEditCourt={setEditingCourt} onCancelEditCourt={() => setEditingCourt(null)} onSaveEditCourt={(draft, id) => saveCourt(venue.id, draft, id)} onDeleteCourt={(court) => deleteCourt(venue.id, court)} />)}</div>;
}

function VenueCard({ venue, editing, onEdit, onCancel, onSave, onDelete, addingCourt, onAddCourt, onCancelCourt, onSaveCourt, editingCourt, onEditCourt, onCancelEditCourt, onSaveEditCourt, onDeleteCourt }: { venue: Venue; editing: boolean; onEdit: () => void; onCancel: () => void; onSave: (draft: VenueDraft) => void; onDelete: () => void; addingCourt: boolean; onAddCourt: () => void; onCancelCourt: () => void; onSaveCourt: (draft: CourtDraft) => void; editingCourt: string | null; onEditCourt: (id: string) => void; onCancelEditCourt: () => void; onSaveEditCourt: (draft: CourtDraft, id: string) => void; onDeleteCourt: (court: Court) => void }) {
  const draft: VenueDraft = { name: venue.name, address: venue.address, district: venue.district, phone: venue.phone ?? '', description: venue.description ?? '', open_time: venue.open_time.slice(0, 5), close_time: venue.close_time.slice(0, 5), deposit_pct: venue.deposit_pct, booking_horizon_days: venue.booking_horizon_days };
  return <section className="overflow-hidden rounded-card border border-hairline bg-card"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-hairline p-5"><div><div className="flex flex-wrap items-center gap-3"><h2 className="font-display text-2xl font-bold text-pitch">{venue.name}</h2><span className="rounded-pill bg-sunk px-2.5 py-1 text-xs">{VENUE_STATUS_LABELS[venue.status]}</span></div><p className="mt-1 text-sm text-ink-secondary">{venue.address} · {venue.district} · {venue.courts.length} sân con</p></div><div className="flex gap-2"><button type="button" onClick={onEdit} className="rounded-control border border-hairline px-3 py-2 text-sm font-semibold text-pitch">Sửa cụm sân</button><button type="button" onClick={onDelete} className="rounded-control border border-hairline px-3 py-2 text-sm font-semibold text-danger">Xóa</button></div></div>{editing && <VenueEditor initial={draft} onCancel={onCancel} onSave={onSave} />}
    <div className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold text-pitch">Sân con</h3><button type="button" onClick={onAddCourt} className="rounded-control bg-pitch px-3 py-2 text-sm font-semibold text-pitch-ink">+ Thêm sân</button></div>{addingCourt && <CourtEditor initial={EMPTY_COURT} onCancel={onCancelCourt} onSave={onSaveCourt} />}{venue.courts.length === 0 ? <p className="mt-4 rounded-control border border-dashed border-strong p-5 text-sm text-ink-secondary">Chưa có sân con.</p> : <ul className="mt-4 divide-y divide-hairline border-y border-hairline">{venue.courts.map((court) => editingCourt === court.id ? <li key={court.id}><CourtEditor initial={toCourtDraft(court)} onCancel={onCancelEditCourt} onSave={(draft) => onSaveEditCourt(draft, court.id)} /> </li> : <li key={court.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-semibold">{court.name} <span className={`ml-2 rounded-pill px-2 py-0.5 text-xs ${court.is_active ? 'bg-free-fill text-free-ink' : 'bg-sunk text-ink-secondary'}`}>{court.is_active ? 'Đang mở' : 'Đang tắt'}</span></p><p className="mt-1 text-sm text-ink-secondary">{SPORT_LABELS[court.sport]} · {court.price_rules?.[0]?.price_per_hour?.toLocaleString('vi-VN') ?? '—'}đ/giờ · {court.slot_minutes} phút{court.is_indoor ? ' · trong nhà' : ''}</p></div><div className="flex gap-2"><button type="button" onClick={() => onEditCourt(court.id)} className="rounded-control border border-hairline px-3 py-2 text-sm font-semibold text-pitch">Sửa</button><button type="button" onClick={() => onDeleteCourt(court)} className="rounded-control border border-hairline px-3 py-2 text-sm font-semibold text-danger">Xóa</button></div></li>)}</ul>}</div></section>;
}

function VenueEditor({ initial, onCancel, onSave }: { initial: VenueDraft; onCancel: () => void; onSave: (draft: VenueDraft) => void }) { const [draft, setDraft] = useState(initial); const set = (key: keyof VenueDraft, value: string | number) => setDraft((current) => ({ ...current, [key]: value })); return <form className="grid gap-4 border-b border-hairline bg-sunk p-5 sm:grid-cols-2" onSubmit={(e) => { e.preventDefault(); onSave(draft); }}><TextField label="Tên cụm sân" value={draft.name} onChange={(v) => set('name', v)} /><TextField label="Số điện thoại" value={draft.phone} onChange={(v) => set('phone', v)} /><TextField label="Địa chỉ" value={draft.address} onChange={(v) => set('address', v)} /><label className="flex flex-col gap-1.5 text-sm font-semibold">Quận/huyện<select className={INPUT} value={draft.district} onChange={(e) => set('district', e.target.value)}>{DISTRICTS.map((d) => <option key={d}>{d}</option>)}</select></label><TextField label="Mở cửa" type="time" value={draft.open_time} onChange={(v) => set('open_time', v)} /><TextField label="Đóng cửa" type="time" value={draft.close_time} onChange={(v) => set('close_time', v)} /><TextField label="Tỷ lệ cọc (%)" type="number" value={String(draft.deposit_pct)} onChange={(v) => set('deposit_pct', Number(v))} /><TextField label="Nhận đặt trước (ngày)" type="number" value={String(draft.booking_horizon_days)} onChange={(v) => set('booking_horizon_days', Number(v))} /><label className="flex flex-col gap-1.5 text-sm font-semibold sm:col-span-2">Giới thiệu<textarea className={`${INPUT} h-20 py-2`} value={draft.description ?? ''} onChange={(e) => set('description', e.target.value)} /></label><div className="flex gap-2 sm:col-span-2"><button className="rounded-control bg-pitch px-4 py-2 text-sm font-semibold text-pitch-ink">Lưu thay đổi</button><button type="button" onClick={onCancel} className="rounded-control border border-hairline px-4 py-2 text-sm font-semibold">Hủy</button></div></form>; }

function CourtEditor({ initial, onCancel, onSave }: { initial: CourtDraft; onCancel: () => void; onSave: (draft: CourtDraft) => void }) { const [draft, setDraft] = useState(initial); const set = (key: keyof CourtDraft, value: string | number | boolean) => setDraft((current) => ({ ...current, [key]: value })); return <form className="mt-4 grid gap-4 rounded-control border border-hairline bg-sunk p-4 sm:grid-cols-2 lg:grid-cols-4" onSubmit={(e) => { e.preventDefault(); onSave(draft); }}><TextField label="Tên sân" value={draft.name} onChange={(v) => set('name', v)} /><label className="flex flex-col gap-1.5 text-sm font-semibold">Môn<select className={INPUT} value={draft.sport} onChange={(e) => set('sport', e.target.value)}>{Object.entries(SPORT_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><TextField label="Giá/giờ" type="number" value={String(draft.price_per_hour)} onChange={(v) => set('price_per_hour', Number(v))} /><label className="flex flex-col gap-1.5 text-sm font-semibold">Khung phút<select className={INPUT} value={draft.slot_minutes} onChange={(e) => set('slot_minutes', Number(e.target.value))}>{[30, 60, 90, 120].map((n) => <option key={n} value={n}>{n} phút</option>)}</select></label><TextField label="Mặt sân" value={draft.surface} required={false} onChange={(v) => set('surface', v)} /><TextField label="Mở riêng (bỏ trống = cụm)" type="time" value={draft.open_time} required={false} onChange={(v) => set('open_time', v)} /><TextField label="Đóng riêng" type="time" value={draft.close_time} required={false} onChange={(v) => set('close_time', v)} /><label className="flex items-center gap-2 self-end text-sm font-semibold"><input type="checkbox" checked={draft.is_indoor} onChange={(e) => set('is_indoor', e.target.checked)} /> Trong nhà</label><label className="flex items-center gap-2 self-end text-sm font-semibold"><input type="checkbox" checked={draft.is_active} onChange={(e) => set('is_active', e.target.checked)} /> Nhận đặt</label><div className="flex gap-2 sm:col-span-2 lg:col-span-4"><button className="rounded-control bg-pitch px-4 py-2 text-sm font-semibold text-pitch-ink">Lưu sân</button><button type="button" onClick={onCancel} className="rounded-control border border-hairline px-4 py-2 text-sm font-semibold">Hủy</button></div></form>; }

function TextField({ label, value, onChange, type = 'text', required = true }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="flex flex-col gap-1.5 text-sm font-semibold">{label}<input className={INPUT} type={type} value={value} onChange={(e) => onChange(e.target.value)} required={required} /></label>; }
function toCourtDraft(court: Court): CourtDraft { return { name: court.name, sport: court.sport, surface: court.surface ?? '', is_indoor: court.is_indoor, slot_minutes: court.slot_minutes, open_time: court.open_time?.slice(0, 5) ?? '', close_time: court.close_time?.slice(0, 5) ?? '', is_active: court.is_active, price_per_hour: court.price_rules?.find((rule) => rule.label === 'Giá chung')?.price_per_hour ?? court.price_rules?.[0]?.price_per_hour ?? 250000 }; }
