import { CANCEL_WINDOW_HOURS, HOLD_MINUTES, MAX_PENDING, MAX_SLOTS } from './constants';

export const HELP_TOPICS = [
  { category: 'Đặt sân', question: 'Làm sao đặt sân và biết giờ nào còn trống?', answer: 'Tìm sân theo môn, khu vực và ngày chơi. Mở sân, chọn môn, thời lượng và giờ còn trống, kiểm tra sân được gợi ý rồi xác nhận. Hệ thống kiểm tra lại lịch và tính giá khi tạo đơn; lịch có thể thay đổi nếu người khác vừa đặt.', href: '/tim-san', link: 'Tìm sân' },
  { category: 'Đặt sân', question: 'Được giữ chỗ bao lâu khi chưa chuyển cọc?', answer: `Một đơn giữ chỗ ${HOLD_MINUTES} phút. Hết hạn chưa xác nhận cọc thì khung giờ được mở lại. Về trang chủ không hủy giữ chỗ; dùng nút hủy nếu muốn trả lịch ngay. Mỗi người có tối đa ${MAX_PENDING} đơn chờ.`, href: '/don-cua-toi', link: 'Kiểm tra đơn của tôi' },
  { category: 'Đặt sân', question: 'Có đặt nhiều sân hoặc nhiều khung giờ cùng lúc được không?', answer: `Mỗi đơn đặt đúng một sân, tối đa ${MAX_SLOTS} khung liền nhau. Nếu nhóm cần hai sân cùng giờ, tạo hai đơn riêng và kiểm tra lịch của từng sân.`, href: '/tim-san', link: 'Chọn sân' },
  { category: 'Thanh toán', question: 'Chuyển cọc vào đâu và bao nhiêu tiền?', answer: 'Dùng đúng tài khoản, số tiền và mã chuyển khoản hiển thị trên đơn của bạn. Mặc định đơn mới cọc toàn bộ tiền sân; số tiền trên đơn là căn cứ thanh toán. Không dùng QR hoặc tài khoản của một đơn khác.', href: '/don-cua-toi', link: 'Mở đơn đã đặt' },
  { category: 'Thanh toán', question: 'Đã chuyển tiền nhưng đơn chưa xác nhận thì làm gì?', answer: 'Kiểm tra mã đơn, tài khoản nhận, số tiền và trạng thái đơn. Hệ thống có thể nhận giao dịch chậm; không chuyển thêm tiền khi chưa rõ kết quả. Nếu quá 5 phút chưa cập nhật, liên hệ hỗ trợ kèm mã đơn và mã giao dịch. Không gửi mật khẩu hoặc OTP.', href: '/gop-y', link: 'Gửi yêu cầu hỗ trợ' },
  { category: 'Thanh toán', question: 'Chuyển tiền sau khi hết hạn giữ chỗ có giữ lại sân không?', answer: 'Tiền vào muộn không khôi phục đơn đã hết hạn. Khoản cần hoàn được ghi nhận để đối soát thủ công. Nếu vẫn muốn chơi, xem lịch hiện tại và tạo đơn mới sau khi kiểm tra rõ giao dịch trước.', href: '/chinh-sach-huy', link: 'Xem chính sách hủy và hoàn cọc' },
  { category: 'Hủy & hoàn cọc', question: 'Hủy sân có được hoàn cọc không?', answer: `Theo chính sách hiện tại, đơn đặt sân dùng mốc ${CANCEL_WINDOW_HOURS} giờ trước buổi chơi để xét hoàn cọc. Xem chính sách và thông tin trên đơn trước khi hủy. Hệ thống ghi nhận khoản cần hoàn, chủ sân chuyển tiền thủ công.`, href: '/chinh-sach-huy', link: 'Đọc chính sách hủy' },
  { category: 'Giải đấu', question: 'Cọc giải đấu và hủy suất khác đặt sân thế nào?', answer: 'Sau khi được duyệt tham gia, đóng cọc bằng mã GIAI và thông tin riêng của suất đăng ký. Giải mới hoàn toàn bộ cọc nếu tự hủy trước ít nhất 24 giờ; muộn hơn không hoàn. Ban tổ chức hủy suất hoặc giải hoàn toàn bộ. Giải cũ giữ chính sách đã công bố; xem đúng điều khoản và hạn của suất.', href: '/giai-dau', link: 'Xem các giải đấu' },
  { category: 'Tài khoản', question: 'Không nhận được OTP hoặc quên mật khẩu?', answer: 'Kiểm tra địa chỉ email, thư rác và thư quảng cáo. Chờ hết thời gian đếm trước khi gửi lại mã. Nếu quên mật khẩu, dùng liên kết khôi phục ở trang đăng nhập. Không chia sẻ mã xác thực với bất kỳ ai.', href: '/quen-mat-khau', link: 'Khôi phục mật khẩu' },
  { category: 'Tài khoản', question: 'Ai thấy số điện thoại trong hồ sơ Kết nối?', answer: 'Hồ sơ mặc định ẩn. Khi đồng ý công khai, bạn vẫn chọn riêng kênh điện thoại, Zalo và Facebook nào được người khác xem. Bỏ công khai hồ sơ để ẩn lại. Kết nối là danh bạ tự liên hệ, không có chat trong website.', href: '/ket-noi/ho-so', link: 'Quản lý hồ sơ Kết nối' },
  { category: 'Tiện ích', question: 'Lưu sân yêu thích có giữ chỗ không?', answer: 'Lưu sân giúp tìm lại nhanh và được đồng bộ theo tài khoản giữa các thiết bị. Nó không giữ giờ chơi hoặc cố định giá. Khi quay lại, mở lịch sân để xem thời gian và giá hiện tại.', href: '/san-yeu-thich', link: 'Sân yêu thích của tôi' },
  { category: 'Tiện ích', question: 'Lịch đã tải có tự cập nhật khi hủy hoặc đổi trạng thái không?', answer: 'Tệp lịch là bản chụp của đơn đã xác nhận tại lúc tải. Nó không tự cập nhật trong ứng dụng lịch khi đơn bị hủy. Kiểm tra Đơn của tôi trước khi ra sân và tự xóa sự kiện cũ nếu cần.', href: '/don-cua-toi', link: 'Xem trạng thái đơn' },
  { category: 'Chủ sân', question: 'Làm sao đưa sân lên website?', answer: 'Gửi hồ sơ tài khoản chủ sân, kết nối SePay và chọn tài khoản nhận cọc. Sau khi admin duyệt, tạo cụm sân nháp, thêm sân con và giá, lưu 3–8 ảnh thật để công khai. Kiểm tra trạng thái nhận đơn và các bước cần hoàn tất trong trang quản lý.', href: '/dang-ky-san', link: 'Đăng ký tài khoản chủ sân' },
  { category: 'Chủ sân', question: 'Phí sử dụng website là bao nhiêu?', answer: 'Mặc định tài khoản được miễn phí. Nếu admin bật thu phí, mức phí là 299.000đ cho một tháng và tất cả cụm sân của chủ sân. Thanh toán ở mục Phí sử dụng website trong trang quản lý; dùng đúng mã PHI và tài khoản trên kỳ phí.', href: '/chu-san/phi-dich-vu', link: 'Kiểm tra phí sử dụng' },
];
