export const dynamic = 'force-dynamic';
import Link from 'next/link';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import { z } from 'zod';
import { createClient } from '@/lib/supabase/server';
import { SPORT_LABELS } from '@/lib/constants';
import { dayLabel, hhmm, vnd } from '@/lib/format';
import { vietQrUrl } from '@/lib/sepay';
import { registrationStatuses, tournamentStatuses, paymentOutcomes } from '@/lib/tournaments';
import { ActionForm } from '@/components/action-form';
import { Field, fieldClass } from '@/components/tournament-fields';
import { TournamentRefresh } from '@/components/tournament-refresh';
export const metadata = { title: 'Chi tiết giải đấu' };
const dateTime = (value: string) => `${dayLabel(new Date(value))} · ${hhmm(value)}`;
export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; if (!z.string().uuid().safeParse(id).success) notFound();
  const db = await createClient(); const { data: { user } } = await db.auth.getUser();
  const { data: t, error } = await db.from('tournaments').select('*').eq('id', id).maybeSingle();
  if (error) throw new Error('Chưa tải được giải đấu.'); if (!t) notFound();
  const [{ data: manager }, { data: admin }, { data: approvedCount }, { data: profile }] = await Promise.all([
    db.rpc('manages_tournament', { p_id: id }), user ? db.rpc('is_admin') : Promise.resolve({ data: false }),
    db.rpc('get_tournament_capacity', { p_id: id }), user ? db.from('profiles').select('full_name,phone').eq('id',user.id).maybeSingle() : Promise.resolve({ data: null }),
  ]);
  let registrationQuery = db.from('tournament_registrations').select('*').eq('tournament_id', id).order('created_at');
  if (!manager) registrationQuery = registrationQuery.eq('user_id', user?.id ?? '00000000-0000-0000-0000-000000000000');
  const { data: registrations, error: registrationError } = user ? await registrationQuery : { data: [], error: null };
  if (registrationError) throw new Error('Chưa tải được danh sách tham gia.');
  const own = registrations?.find(r => r.user_id === user?.id);
  const { data: court } = t.court_id ? await db.from('courts').select('name,venues(name,owner_id)').eq('id',t.court_id).returns<{ name: string; venues: { name: string; owner_id: string } }[]>().maybeSingle() : { data: null };
  const { data: courts, error: courtsError } = admin && t.status === 'pending' ? await db.from('courts').select('id,name,venues!inner(name,status)').eq('sport',t.sport).eq('is_active',true).eq('venues.status','active').returns<{ id: string; name: string; venues: { name: string; status: string } }[]>() : { data: [], error: null };
  if (courtsError) throw new Error('Chưa tải được sân để duyệt.');
  const ids = registrations?.map(r => r.id) ?? [];
  const { data: payments, error: paymentsError } = ids.length ? await db.from('tournament_payment_events').select('transaction_key,registration_id,amount,outcome,refund_amount,refunded_amount,refund_status,created_at').in('registration_id',ids).order('created_at', { ascending: false }) : { data: [], error: null };
  if (paymentsError) throw new Error('Chưa tải được giao dịch.');
  const closed = t.status !== 'published' || Date.parse(t.registration_deadline) <= Date.now();
  const started = Date.parse(t.starts_at) <= Date.now();
  return <main className="mx-auto max-w-6xl px-5 py-10 lg:px-12">
    <TournamentRefresh id={id} deadline={t.registration_deadline} />
    <Link href="/giai-dau" className="text-sm font-semibold text-pitch">← Giải đấu</Link>
    <header className="my-7"><p className="text-sm font-semibold text-pitch">{SPORT_LABELS[t.sport]} · {tournamentStatuses[t.status]}</p><h1 className="mt-3 font-display text-4xl font-extrabold text-pitch">{t.title}</h1></header>
    <div className="grid gap-6 lg:grid-cols-[1fr_320px]"><section className="rounded-card border border-hairline bg-card p-6"><h2 className="font-display text-xl font-bold text-pitch">Thông tin & thể lệ</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-7">{t.description}</p>
      <dl className="mt-6 grid gap-4 text-sm sm:grid-cols-2">{[['Địa điểm',t.address],['Sân',court ? `${court.venues?.name} · ${court.name}` : 'Admin đang bố trí'],['Bắt đầu',dateTime(t.starts_at)],['Kết thúc',dateTime(t.ends_at)],['Hạn đăng ký và đóng cọc',dateTime(t.registration_deadline)],['Quy mô',`${t.capacity} suất · ${approvedCount ?? 0} đã được duyệt`]].map(([label,value]) => <div key={label}><dt className="text-ink-secondary">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>)}</dl>
      {t.review_note && <p className="mt-5 rounded-control bg-sunk p-4 text-sm">Ghi chú admin: {t.review_note}</p>}
    </section><aside className="h-fit rounded-card border border-hairline bg-card p-6"><p className="text-sm text-ink-secondary">Lệ phí mỗi suất</p><p className="mt-2 font-display text-3xl font-bold text-pitch">{vnd(t.entry_fee)}</p><p className="mt-3 text-sm">Cọc {vnd(t.deposit_amount)} · còn lại {vnd(t.entry_fee-t.deposit_amount)}</p><p className="mt-4 text-xs leading-6 text-ink-secondary">Chuyển cọc sau khi được duyệt. SePay xác nhận tự động; tiền vào tài khoản chủ sân. Hủy trước giờ bắt đầu được hoàn cọc, chủ sân thực hiện thủ công. Quá giờ bắt đầu, liên hệ ban tổ chức.</p></aside></div>
    {admin && t.status === 'pending' && <section className="mt-6 rounded-card border border-hairline bg-card p-6"><h2 className="mb-4 font-display text-xl font-bold text-pitch">Duyệt & bố trí sân</h2><p className="mb-4 text-sm text-ink-secondary">Duyệt sẽ khóa lịch sân trong thời gian giải và cấp quyền quản lý cho người đề xuất. Cọc luôn về chủ sân được chọn.</p>
      <ActionForm payload={{ action: 'review', id }} label="Lưu kết quả duyệt"><Field label="Kết quả"><select className={fieldClass} name="approve"><option value="true">Duyệt và công khai</option><option value="false">Không duyệt</option></select></Field><Field label="Sân tổ chức"><select className={fieldClass} name="court_id" defaultValue={t.court_id ?? ''}><option value="">Chọn sân để duyệt</option>{courts?.map(c => <option key={c.id} value={c.id}>{c.venues?.name} · {c.name}</option>)}</select></Field><Field label="Ghi chú / lý do không duyệt"><textarea className={fieldClass} name="note" maxLength={1000} rows={3} /></Field></ActionForm>
    </section>}
    {own ? <section className="mt-6 rounded-card border border-hairline bg-card p-6"><h2 className="font-display text-xl font-bold text-pitch">Đăng ký của bạn</h2><p className="mt-3 text-sm">{registrationStatuses[own.status]} · {own.paid_at ? 'Đã nhận cọc' : own.deposit_amount === 0 ? 'Không yêu cầu cọc' : 'Chưa nhận đủ cọc'}</p>{own.review_note && <p className="mt-2 text-sm">Ghi chú: {own.review_note}</p>}
      {own.status === 'approved' && !own.paid_at && own.deposit_amount > 0 && !closed && own.bank && own.account_number && <div className="my-6 grid gap-6 sm:grid-cols-[220px_1fr]">
        <Image unoptimized width={220} height={270} className="w-[220px] max-w-full rounded-control border border-hairline" src={vietQrUrl(own.code,own.deposit_amount,own.bank,own.account_number)} alt={`QR chuyển cọc ${vnd(own.deposit_amount)}, nội dung ${own.code}`} />
        <div className="space-y-3 text-sm"><p>Ngân hàng: <strong>{own.bank}</strong></p><p>Số tài khoản: <strong>{own.account_number}</strong></p><p>Người nhận: <strong>{own.account_name}</strong></p><p>Số tiền: <strong>{vnd(own.deposit_amount)}</strong></p><p>Nội dung: <strong className="break-all">{own.code}</strong></p><p role="status" className="text-peak-ink">Chờ chuyển khoản. Trang tự cập nhật khi nhận đủ cọc.</p><p className="text-xs leading-6 text-ink-secondary">Giữ nguyên mã, chuyển đủ cọc trong một giao dịch trước hạn. Không cộng dồn khoản thiếu; nếu đã chuyển thiếu hoặc trùng, liên hệ chủ sân để hoàn và đối soát.</p></div>
      </div>}
      {!started && ['pending','approved'].includes(own.status) && <div className="mt-4"><ActionForm payload={{ action: 'cancel_registration', id: own.id }} label="Hủy tham gia" confirmMessage="Hủy đăng ký tham gia giải? Nếu đã chuyển cọc, chủ sân sẽ hoàn thủ công." /></div>}
    </section> : !closed && (approvedCount ?? 0) < t.capacity ? <section className="mt-6 rounded-card border border-hairline bg-card p-6"><h2 className="mb-5 font-display text-xl font-bold text-pitch">Đăng ký tham gia</h2>{user ? <ActionForm payload={{ action: 'register', id }} nested label="Gửi đăng ký"><div className="grid gap-4 sm:grid-cols-2"><Field label="Họ tên người tham gia / đại diện"><input className={fieldClass} name="full_name" defaultValue={profile?.full_name ?? ''} minLength={2} maxLength={100} required /></Field><Field label="Số điện thoại"><input className={fieldClass} name="phone" type="tel" defaultValue={profile?.phone ?? ''} maxLength={25} required /></Field><Field label="Địa chỉ / khu vực"><input className={fieldClass} name="address" minLength={2} maxLength={300} required /></Field><Field label="Tên đội (nếu thi đấu theo đội)"><input className={fieldClass} name="team_name" maxLength={100} /></Field></div><Field label="Trình độ, thành viên và ghi chú"><textarea className={fieldClass} name="note" maxLength={1000} rows={3} /></Field><p className="text-sm text-ink-secondary">Đăng ký {t.capacity} suất tối đa; lệ phí {vnd(t.entry_fee)}, cọc {vnd(t.deposit_amount)} sau khi được duyệt.</p></ActionForm> : <Link href={`/dang-nhap?next=/giai-dau/${id}`} className="font-semibold text-pitch underline">Đăng nhập để tham gia</Link>}</section> : <p className="mt-6 text-sm text-ink-secondary">{closed ? 'Giải chưa mở hoặc đã đóng đăng ký.' : 'Giải đã đủ suất được duyệt.'}</p>}
    {manager && <section className="mt-8"><h2 className="font-display text-2xl font-bold text-pitch">Quản lý người tham gia ({registrations?.length ?? 0})</h2><p className="mt-2 text-sm text-ink-secondary">Duyệt một đăng ký giữ một suất đến hạn đóng cọc. Chủ sân và người đề xuất giải đều được quản lý danh sách.</p><div className="mt-4 space-y-4">{registrations?.map(r => <article key={r.id} className="rounded-card border border-hairline bg-card p-5"><h3 className="font-semibold">{r.full_name}{r.team_name && ` · ${r.team_name}`}</h3><p className="mt-2 text-sm">{r.phone} · {r.address}</p><p className="mt-2 whitespace-pre-wrap text-sm text-ink-secondary">{r.note}</p><p className="my-3 text-sm font-semibold text-pitch">{registrationStatuses[r.status]} · {r.paid_at ? `Đã cọc ${vnd(r.deposit_amount)}` : r.deposit_amount === 0 ? 'Không cần cọc' : 'Chưa nhận đủ cọc'}</p>
      {r.status === 'pending' && !closed && <ActionForm payload={{ action: 'review_registration', id: r.id }} label="Lưu duyệt đăng ký"><div className="grid gap-3 sm:grid-cols-2"><Field label="Quyết định"><select className={fieldClass} name="approve"><option value="true">Duyệt tham gia</option><option value="false">Từ chối</option></select></Field><Field label="Ghi chú"><input className={fieldClass} name="note" maxLength={1000} /></Field></div></ActionForm>}
      {r.status === 'approved' && !started && <ActionForm payload={{ action: 'cancel_registration', id: r.id }} label="Hủy suất tham gia" confirmMessage="Hủy suất này và ghi nhận cần hoàn cọc đã nhận?" />}
    </article>)}</div>{!registrations?.length && <p className="mt-4 text-sm text-ink-secondary">Chưa có đăng ký.</p>}</section>}
    {!!payments?.length && <section className="mt-8"><h2 className="font-display text-2xl font-bold text-pitch">Giao dịch cọc & đối soát</h2><ul className="mt-4 space-y-3">{payments.map(p => { const r = registrations?.find(r => r.id === p.registration_id); return <li key={p.transaction_key} className="rounded-card border border-hairline bg-card p-5 text-sm"><p className="font-semibold">{r?.full_name} · {vnd(p.amount)} · {paymentOutcomes[p.outcome] ?? p.outcome}</p><p className="mt-2 break-all text-xs text-ink-secondary">{dateTime(p.created_at)} · Mã giao dịch: {p.transaction_key.split(':').at(-1)}</p>{p.refund_amount > 0 && <p className="my-3">{p.refund_status === 'done' ? `Đã hoàn ${vnd(p.refunded_amount)}` : `Cần hoàn ${vnd(p.refund_amount-p.refunded_amount)}`}</p>}{p.refund_status === 'needed' && (admin || r?.payment_owner_id === user?.id) && <ActionForm payload={{ action: 'refund', transaction_key: p.transaction_key, expected_amount: p.refund_amount-p.refunded_amount }} label="Đã chuyển tiền hoàn" confirmMessage={`Xác nhận đã hoàn ${vnd(p.refund_amount-p.refunded_amount)} qua ngân hàng? Thao tác này chỉ ghi nhận, không tự chuyển tiền.`} />}</li>; })}</ul></section>}
    {manager && !started && ['pending','published'].includes(t.status) && <section className="mt-8 border-t border-hairline pt-6"><ActionForm payload={{ action: 'cancel', id }} label="Hủy giải đấu" confirmMessage="Hủy giải, trả lịch sân và ghi nhận các khoản cọc cần hoàn?" /></section>}
  </main>;
}
