export const dynamic = 'force-dynamic';
import Link from 'next/link';
import { TournamentPaymentQr } from '@/components/tournament-payment-qr';
import { notFound } from 'next/navigation';
import { z } from 'zod';
import { createClient } from '@/lib/supabase/server';
import { SPORT_LABELS } from '@/lib/constants';
import { dayLabel, hhmm, vnd } from '@/lib/format';
import { vietQrUrl } from '@/lib/sepay';
import { registrationStatuses, tournamentStatuses, paymentOutcomes, type Registration } from '@/lib/tournaments';
import { TournamentSettlementPanel } from '@/components/tournament-settlement';
import { CopyValue } from '@/components/copy-value';
import { ActionForm } from '@/components/action-form';
import { Field, fieldClass } from '@/components/form-field';
import { TournamentRefresh } from '@/components/tournament-refresh';
export const metadata = { title: 'Chi tiết giải đấu' };
const dateTime = (value: string) => `${dayLabel(new Date(value))} · ${hhmm(value)}`;
export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; if (!z.string().uuid().safeParse(id).success) notFound();
  const db = await createClient(); const { data: { user } } = await db.auth.getUser();
  const { data: t, error } = await db.from('tournaments').select('*').eq('id', id).maybeSingle();
  if (error) throw new Error('Chưa tải được giải đấu.'); if (!t) notFound();
  const [{ data: manager, error: managerError }, { data: admin, error: adminError }, { data: approvedCount, error: capacityError }, { data: profile }] = await Promise.all([
    db.rpc('manages_tournament', { p_id: id }), user ? db.rpc('is_admin') : Promise.resolve({ data: false, error: null }),
    db.rpc('get_tournament_capacity', { p_id: id }), user ? db.from('profiles').select('full_name,phone').eq('id',user.id).maybeSingle() : Promise.resolve({ data: null }),
  ]);
  if (managerError || adminError || capacityError) throw new Error('Chưa tải được quyền quản lý hoặc số suất tham gia.');
  const { data: registrationData, error: registrationError } = user ? await db.rpc('get_tournament_registrations', { p_id: id }) : { data: [], error: null };
  if (registrationError) {
    console.error('get_tournament_registrations', registrationError.code, registrationError.message);
    throw new Error('Chưa tải được danh sách tham gia.');
  }
  const registrations = (registrationData ?? []) as Registration[];
  const own = registrations?.find(r => r.user_id === user?.id);
  const { data: court } = t.court_id ? await db.from('courts').select('name,venues(name,owner_id)').eq('id',t.court_id).returns<{ name: string; venues: { name: string; owner_id: string } }[]>().maybeSingle() : { data: null };
  const { data: courts, error: courtsError } = admin && t.status === 'pending' ? await db.from('courts').select('id,name,venues!inner(name,status)').eq('sport',t.sport).eq('is_active',true).eq('venues.status','active').returns<{ id: string; name: string; venues: { name: string; status: string } }[]>() : { data: [], error: null };
  if (courtsError) throw new Error('Chưa tải được sân để duyệt.');
  const ids = registrations?.map(r => r.id) ?? [];
  const { data: payments, error: paymentsError } = ids.length ? await db.from('tournament_payment_events').select('transaction_key,registration_id,amount,outcome,refund_amount,refunded_amount,refund_status,created_at').in('registration_id',ids).order('created_at', { ascending: false }) : { data: [], error: null };
  if (paymentsError) throw new Error('Chưa tải được giao dịch.');
  const closed = t.status !== 'published' || Date.parse(t.registration_deadline) <= Date.now();
  const canRegisterAgain = !own || ['cancelled','expired','rejected'].includes(own.status);
  const payClosed = !own?.payment_expires_at || Date.parse(own.payment_expires_at) <= Date.now() || t.status !== 'published';
  const started = Date.parse(t.starts_at) <= Date.now();
  const nextStep = own ? own.status === 'pending' ? 'Ban tổ chức đang xem đăng ký. Bạn chưa cần chuyển cọc; kết quả sẽ cập nhật tại đây.'
    : own.status === 'approved' ? own.paid_at || own.deposit_amount === 0 ? 'Bạn đã hoàn tất đăng ký. Xem lại lịch, địa điểm và thể lệ để chuẩn bị ra sân.'
      : payClosed ? 'Đã hết hạn đóng cọc. Liên hệ ban tổ chức để kiểm tra suất tham gia; không chuyển thêm tiền.'
      : `Bạn đã được duyệt. Chuyển đủ cọc trước ${dateTime(own.payment_expires_at!)} để hoàn tất đăng ký.`
    : own.status === 'expired' ? 'Đăng ký đã hết hạn. Suất đã được trả lại; bạn có thể gửi đăng ký mới nếu giải còn nhận người.'
    : own.status === 'rejected' ? 'Đăng ký chưa được chấp nhận. Xem ghi chú của ban tổ chức bên dưới.'
    : 'Đăng ký đã hủy. Nếu đã chuyển tiền, xem mục giao dịch và liên hệ chủ sân để đối soát hoàn cọc.' : '';
  const registrationForm = <><h2 className="mb-3 font-display text-2xl font-bold text-pitch">Đăng ký tham gia</h2><p className="mb-6 text-sm leading-7 text-ink-secondary">Gửi thông tin để ban tổ chức xét duyệt. Bạn chưa cần thanh toán ở bước này.</p>{user ? <ActionForm payload={{ action: 'register', id }} nested label="Gửi đăng ký" successMessage="Đã gửi đăng ký. Ban tổ chức sẽ xem và duyệt."><div className="grid gap-4 sm:grid-cols-2"><Field label="Họ tên người tham gia / đại diện"><input className={fieldClass} name="full_name" defaultValue={profile?.full_name ?? ''} minLength={2} maxLength={100} required /></Field><Field label="Số điện thoại"><input className={fieldClass} name="phone" type="tel" defaultValue={profile?.phone ?? ''} maxLength={25} required /></Field><Field label="Địa chỉ / khu vực"><input className={fieldClass} name="address" minLength={2} maxLength={300} required /></Field><Field label="Tên đội (nếu thi đấu theo đội)"><input className={fieldClass} name="team_name" maxLength={100} /></Field></div><Field label="Trình độ, thành viên và ghi chú"><textarea className={fieldClass} name="note" maxLength={1000} rows={3} /></Field><p className="text-sm text-ink-secondary">Đăng ký {t.capacity} suất tối đa; lệ phí {vnd(t.entry_fee)}, cọc {vnd(t.deposit_amount)} sau khi được duyệt.</p></ActionForm> : <Link href={`/dang-nhap?next=/giai-dau/${id}`} className="font-semibold text-pitch underline">Đăng nhập để tham gia</Link>}</>;
  return <main className="mx-auto max-w-6xl px-5 py-10 lg:px-12">
    <TournamentRefresh id={id} deadlines={[t.registration_deadline,t.payment_deadline,t.starts_at,t.ends_at,...(registrations ?? []).flatMap(r => r.payment_expires_at ? [r.payment_expires_at] : [])]} />
    <Link href="/giai-dau" className="text-sm font-semibold text-pitch">← Giải đấu</Link>
    <header className="my-7 overflow-hidden rounded-[24px] border border-strong bg-free-fill p-6 sm:p-9"><div className="flex flex-wrap items-center gap-3"><span className="text-xs font-bold uppercase tracking-widest text-pitch">{SPORT_LABELS[t.sport]}</span><span className={`rounded-full border px-3 py-1 text-xs font-semibold ${t.status === 'pending' ? 'border-peak-line bg-peak-fill text-peak-ink' : 'border-strong bg-card text-pitch'}`}>{tournamentStatuses[t.status]}</span></div><h1 className="mt-5 max-w-3xl break-words font-display text-3xl font-extrabold leading-tight tracking-tight text-pitch sm:text-5xl">{t.title}</h1><p className="mt-5 text-sm font-semibold text-pitch">{dateTime(t.starts_at)}</p><p className="mt-2 break-words text-sm leading-6 text-ink-secondary">{t.address}</p></header>
    {manager && <section className="mb-6 rounded-card border border-hairline bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-display text-xl font-bold text-pitch">Khu vực quản lý giải</h2><p className="mt-2 text-sm text-ink-secondary">{t.status === 'pending' ? 'Đề xuất đang chờ admin duyệt và xác nhận sân tổ chức.' : `${registrations?.filter(r => r.status === 'pending').length ?? 0} chờ duyệt · ${registrations?.filter(r => r.status === 'approved' && !r.paid_at && r.deposit_amount > 0).length ?? 0} chưa đủ cọc`}</p></div><a href={admin && t.status === 'pending' ? '#duyet-giai' : '#nguoi-tham-gia'} className="inline-flex min-h-11 items-center rounded-control bg-pitch px-5 text-sm font-semibold text-pitch-ink">{admin && t.status === 'pending' ? 'Duyệt đề xuất ↓' : 'Quản lý người tham gia ↓'}</a></div></section>}
    {own && <div className={`mb-6 rounded-card border p-5 ${own.status === 'pending' || (own.status === 'approved' && !own.paid_at && own.deposit_amount > 0) ? 'border-peak-line bg-peak-fill' : 'border-strong bg-free-fill'}`}><p className="font-semibold text-pitch">{registrationStatuses[own.status]}{own.paid_at ? ' · Đã nhận cọc' : ''}</p><p className="mt-2 text-sm leading-7">{nextStep}</p><a href="#dang-ky" className="mt-2 inline-flex min-h-11 items-center text-sm font-semibold text-pitch underline underline-offset-4">Xem đăng ký của bạn ↓</a></div>}
    <div className="grid items-start gap-6 lg:grid-cols-[1fr_320px]">
      <section className="min-w-0 rounded-card border border-hairline bg-card p-6 sm:p-7"><h2 className="font-display text-2xl font-bold text-pitch">Lịch & địa điểm</h2><dl className="mt-5 grid gap-5 text-sm sm:grid-cols-2">{[['Sân tổ chức',court ? `${court.venues?.name} · ${court.name}` : 'Admin đang bố trí'],['Địa điểm',t.address],['Bắt đầu',dateTime(t.starts_at)],['Kết thúc',dateTime(t.ends_at)],['Hạn nhận / duyệt đăng ký',dateTime(t.registration_deadline)],['Hạn đóng cọc cuối cùng',dateTime(t.payment_deadline)],['Thời gian cọc sau duyệt',`${t.payment_hold_hours} giờ, không vượt hạn cuối`],['Quy mô',`${t.capacity} suất · ${approvedCount ?? 0} đã được duyệt`]].map(([label,value]) => <div key={label} className="border-b border-hairline pb-4"><dt className="text-xs text-ink-secondary">{label}</dt><dd className="mt-2 break-words font-semibold leading-6">{value}</dd></div>)}</dl><h2 className="mt-8 font-display text-2xl font-bold text-pitch">Thông tin & thể lệ</h2><p className="mt-4 whitespace-pre-wrap break-words text-sm leading-7">{t.description}</p>{t.review_note && <p className="mt-5 rounded-control bg-sunk p-4 text-sm leading-7">Ghi chú admin: {t.review_note}</p>}</section>
      <aside className="rounded-card border border-strong bg-card p-6 lg:sticky lg:top-24"><p className="text-sm text-ink-secondary">Lệ phí mỗi suất</p><p className="mt-2 font-display text-4xl font-bold tracking-tight text-pitch">{t.entry_fee ? vnd(t.entry_fee) : 'Miễn phí'}</p><dl className="mt-5 space-y-3 border-y border-hairline py-4 text-sm"><div className="flex justify-between gap-3"><dt className="text-ink-secondary">Cọc sau khi duyệt</dt><dd className="font-semibold">{vnd(t.deposit_amount)}</dd></div><div className="flex justify-between gap-3"><dt className="text-ink-secondary">Nộp khi tham gia</dt><dd className="font-semibold">{vnd(t.entry_fee-t.deposit_amount)}</dd></div></dl>
        {!manager && <a href="#dang-ky" className="mt-5 flex min-h-12 items-center justify-center rounded-control bg-pitch px-4 text-center text-sm font-semibold text-pitch-ink">{own ? 'Xem đăng ký của bạn' : !closed && (approvedCount ?? 0) < t.capacity ? 'Đăng ký tham gia ↓' : 'Xem trạng thái đăng ký'}</a>}
        <p className="mt-4 text-xs leading-6 text-ink-secondary">Chuyển cọc sau khi được duyệt. Phần còn lại nộp trực tiếp, không dùng lại mã chuyển cọc. SePay xác nhận tự động; tiền vào tài khoản chủ sân. {t.cancel_window_hours === 24 ? 'Tự hủy trước giờ thi đấu ít nhất 24 giờ: hoàn 100% cọc; muộn hơn không hoàn cọc.' : 'Giải cũ: tự hủy trước giờ bắt đầu được hoàn 100% cọc.'} Ban tổ chức hủy suất hoặc hủy cả giải: hoàn 100%. Chủ sân hoàn thủ công.</p>
      </aside>
    </div>
    {admin && t.status === 'pending' && <section id="duyet-giai" className="scroll-mt-28 mt-6 rounded-card border border-hairline bg-card p-6"><h2 className="mb-4 font-display text-xl font-bold text-pitch">Duyệt & bố trí sân</h2><p className="mb-4 text-sm text-ink-secondary">Duyệt sẽ khóa lịch sân trong thời gian giải và cấp quyền quản lý cho người đề xuất. Cọc luôn về chủ sân được chọn.</p>
      <ActionForm payload={{ action: 'review', id }} label="Lưu kết quả duyệt"><Field label="Kết quả"><select className={fieldClass} name="approve"><option value="true">Duyệt và công khai</option><option value="false">Không duyệt</option></select></Field><Field label="Sân tổ chức"><select className={fieldClass} name="court_id" defaultValue={t.court_id ?? ''}><option value="">Chọn sân để duyệt</option>{courts?.map(c => <option key={c.id} value={c.id}>{c.venues?.name} · {c.name}</option>)}</select></Field><Field label="Tiền thuê sân đã thỏa thuận (đ)"><input className={fieldClass} type="number" name="venue_fee" min={0} max={100000000} defaultValue={0} required /></Field><Field label="Tiền thuê khi người tổ chức hủy cả giải (đ)"><input className={fieldClass} type="number" name="cancellation_venue_fee" min={0} max={100000000} defaultValue={0} required /></Field><Field label="Thỏa thuận thu phí và thuê sân"><textarea className={fieldClass} name="terms_note" maxLength={1000} rows={3} placeholder="Ghi số tiền thuê, người tổ chức chịu phần thiếu; chủ sân thu toàn bộ lệ phí. Chốt riêng tiền thuê khi người tổ chức hủy; chủ sân hủy thì không tính tiền thuê. Hai bên quyết toán trong 7 ngày sau giải." /></Field><label className="flex items-start gap-3 rounded-control bg-free-fill p-4 text-sm leading-7"><input className="mt-1.5 size-5 shrink-0 accent-pitch" type="checkbox" name="terms_confirmed" />Chủ sân và người tổ chức đã đồng ý thỏa thuận, cách thu/hoàn và quyết toán. Bắt buộc khi duyệt công khai.</label><Field label="Ghi chú / lý do không duyệt"><textarea className={fieldClass} name="note" maxLength={1000} rows={3} /></Field></ActionForm>
    </section>}
    {own ? <section id="dang-ky" className="scroll-mt-28 mt-6 rounded-card border border-hairline bg-card p-6"><h2 className="font-display text-xl font-bold text-pitch">Đăng ký của bạn</h2><p className="mt-3 text-sm">{registrationStatuses[own.status]} · {own.paid_at ? 'Đã nhận cọc' : own.deposit_amount === 0 ? 'Không yêu cầu cọc' : 'Chưa nhận đủ cọc'}</p>{own.balance_received_at && <p className="mt-2 text-sm text-pitch">Đã nhận phần lệ phí còn lại: {vnd(own.entry_fee-own.deposit_amount)}</p>}{own.balance_refund_due > 0 && <p className="mt-2 text-sm">{own.balance_refunded_at ? 'Đã hoàn' : 'Cần hoàn'} phần lệ phí còn lại: {vnd(own.balance_refund_due)}</p>}{own.review_note && <p className="mt-2 text-sm">Ghi chú: {own.review_note}</p>}
      {own.status === 'approved' && !own.paid_at && own.deposit_amount > 0 && !payClosed && own.bank && own.account_number && <div className="my-6 grid gap-6 sm:grid-cols-[220px_1fr]">
        <TournamentPaymentQr src={vietQrUrl(own.code,own.deposit_amount,own.bank,own.account_number)} alt={`QR chuyển cọc ${vnd(own.deposit_amount)}, nội dung ${own.code}`} />
        <div className="space-y-3 text-sm"><p>Ngân hàng: <strong>{own.bank}</strong></p><p>Số tài khoản: <CopyValue label="số tài khoản" value={own.account_number} /></p><p>Người nhận: <strong>{own.account_name}</strong></p><p>Số tiền: <strong>{vnd(own.deposit_amount)}</strong></p><p>Nội dung: <CopyValue label="nội dung chuyển khoản" value={own.code} /></p><p className="font-semibold">Hạn cọc của bạn: {dateTime(own.payment_expires_at!)}</p><p role="status" className="text-peak-ink">Chờ chuyển khoản. Trang tự cập nhật khi nhận đủ cọc.</p><p className="text-xs leading-6 text-ink-secondary">Giữ nguyên mã, chuyển đủ cọc trong một giao dịch trước hạn. Không cộng dồn khoản thiếu; nếu đã chuyển thiếu hoặc trùng, liên hệ chủ sân để hoàn và đối soát.</p></div>
      </div>}
      {canRegisterAgain && !closed && <a href="#dang-ky-lai" className="mt-3 inline-flex min-h-11 items-center font-semibold text-pitch underline">Gửi đăng ký mới ↓</a>}
      {!started && ['pending','approved'].includes(own.status) && <div className="mt-4"><ActionForm payload={{ action: 'cancel_registration', id: own.id }} variant="danger" label="Hủy tham gia" confirmMessage={`Hủy đăng ký? ${own.refund_deadline ? `Chỉ hoàn cọc nếu bạn hủy không muộn hơn ${dateTime(own.refund_deadline)}. Sau mốc này không hoàn cọc.` : 'Xem chính sách hoàn cọc của giải.'}`}  /></div>}
    </section> : null}
    {canRegisterAgain && !closed && (approvedCount ?? 0) < t.capacity ? <section id={own ? 'dang-ky-lai' : 'dang-ky'} className="scroll-mt-28 mt-6 rounded-card border border-hairline bg-card p-6">{manager ? <details><summary className="min-h-11 cursor-pointer text-sm font-semibold text-pitch">Tôi cũng muốn đăng ký một suất tham gia</summary><div className="mt-5">{registrationForm}</div></details> : registrationForm}</section> : !own && !manager ? <p id="dang-ky" className="mt-6 scroll-mt-28 rounded-card border border-hairline bg-sunk p-5 text-sm text-ink-secondary">{closed ? 'Giải chưa mở hoặc đã đóng đăng ký.' : 'Giải đã đủ suất được duyệt.'} <Link href="/giai-dau" className="font-semibold text-pitch underline">Khám phá giải khác</Link></p> : null}
    {manager && <section id="nguoi-tham-gia" className="mt-8 scroll-mt-28"><h2 className="font-display text-2xl font-bold text-pitch">Quản lý người tham gia ({registrations?.length ?? 0})</h2><p className="mt-2 text-sm text-ink-secondary">Duyệt một đăng ký giữ một suất đến hạn đóng cọc. Chủ sân và người đề xuất giải đều được quản lý danh sách.</p><div className="mt-4 space-y-4">{registrations?.toSorted((a, b) => Number(b.status === 'pending') - Number(a.status === 'pending')).map(r => <article key={r.id} className="rounded-card border border-hairline bg-card p-5"><h3 className="font-semibold">{r.full_name}{r.team_name && ` · ${r.team_name}`}</h3><p className="mt-2 text-sm">{r.phone} · {r.address}</p><p className="mt-2 whitespace-pre-wrap text-sm text-ink-secondary">{r.note}</p><p className="my-3 text-sm font-semibold text-pitch">{registrationStatuses[r.status]} · {r.paid_at ? `Đã cọc ${vnd(r.deposit_amount)}` : r.deposit_amount === 0 ? 'Không cần cọc' : 'Chưa nhận đủ cọc'}</p>
      {r.status === 'pending' && !closed && <ActionForm payload={{ action: 'review_registration', id: r.id }} label="Lưu duyệt đăng ký"><div className="grid gap-3 sm:grid-cols-2"><Field label="Quyết định"><select className={fieldClass} name="approve"><option value="true">Duyệt tham gia</option><option value="false">Từ chối</option></select></Field><Field label="Ghi chú"><input className={fieldClass} name="note" maxLength={1000} /></Field></div></ActionForm>}
      {r.status === 'approved' && t.status === 'published' && Date.parse(t.ends_at) > Date.now() && <ActionForm payload={{ action: 'cancel_registration', id: r.id }} variant="danger" label="Hủy suất tham gia" confirmMessage="Hủy suất này và ghi nhận cần hoàn cọc đã nhận?" />}
      {(admin || r.payment_owner_id === user?.id) && <div className="mt-4 space-y-4 border-t border-hairline pt-4">
        <p className="text-sm text-ink-secondary">Phần lệ phí còn lại: {vnd(r.entry_fee-r.deposit_amount)} · {r.balance_received_at ? 'Đã thu' : r.balance_waived_at ? 'Đã miễn / vắng mặt' : 'Chưa thu'}</p>
        {r.balance_receipt && <p className="break-words text-xs text-ink-secondary">Chứng từ / ghi chú: {r.balance_receipt}</p>}
        {started && r.status === 'approved' && (r.paid_at || r.deposit_amount === 0) && r.entry_fee > r.deposit_amount && !r.balance_received_at && !r.balance_waived_at && <><ActionForm payload={{ action: 'balance', id: r.id, refund: false }} label={`Đã thu thêm ${vnd(r.entry_fee-r.deposit_amount)}`} confirmMessage="Xác nhận chủ sân đã nhận số tiền này? Không ghi lại khoản cọc đã được SePay xác nhận."><Field label="Chứng từ / ghi chú thu tiền"><input className={fieldClass} name="receipt" minLength={3} maxLength={300} required /></Field></ActionForm><details><summary className="min-h-11 text-sm font-semibold text-pitch">Vắng mặt hoặc miễn phần còn lại</summary><ActionForm payload={{ action: 'waive_balance', id: r.id }} label="Ghi nhận không thu thêm" confirmMessage="Xác nhận không thu phần lệ phí còn lại? Khoản cọc đã nhận giữ theo chính sách hủy."><Field label="Lý do miễn / vắng mặt"><input className={fieldClass} name="note" minLength={3} maxLength={300} required /></Field></ActionForm></details></>}
        {r.balance_refund_due > 0 && !r.balance_refunded_at && <ActionForm payload={{ action: 'balance', id: r.id, refund: true }} label={`Đã hoàn lệ phí còn lại ${vnd(r.balance_refund_due)}`} confirmMessage="Chỉ xác nhận sau khi chuyển trả tiền cho người tham gia."><Field label="Chứng từ hoàn tiền"><input className={fieldClass} name="receipt" minLength={3} maxLength={300} required /></Field></ActionForm>}
      </div>}
    </article>)}</div>{!registrations?.length && <p className="mt-4 text-sm text-ink-secondary">Chưa có đăng ký.</p>}</section>}
    {!!payments?.length && <section className="mt-8"><h2 className="font-display text-2xl font-bold text-pitch">Giao dịch cọc & đối soát</h2><ul className="mt-4 space-y-3">{payments.map(p => { const r = registrations?.find(r => r.id === p.registration_id); return <li key={p.transaction_key} className="rounded-card border border-hairline bg-card p-5 text-sm"><p className="font-semibold">{r?.full_name} · {vnd(p.amount)} · {paymentOutcomes[p.outcome] ?? p.outcome}</p><p className="mt-2 break-all text-xs text-ink-secondary">{dateTime(p.created_at)} · Mã giao dịch: {p.transaction_key.split(':').at(-1)}</p>{p.refund_amount > 0 && <p className="my-3">{p.refund_status === 'done' ? `Đã hoàn ${vnd(p.refunded_amount)}` : `Cần hoàn ${vnd(p.refund_amount-p.refunded_amount)}`}</p>}{p.refund_status === 'needed' && (admin || r?.payment_owner_id === user?.id) && <ActionForm payload={{ action: 'refund', transaction_key: p.transaction_key, expected_amount: p.refund_amount-p.refunded_amount }} label="Đã chuyển tiền hoàn" confirmMessage={`Xác nhận đã hoàn ${vnd(p.refund_amount-p.refunded_amount)} qua ngân hàng? Thao tác này chỉ ghi nhận, không tự chuyển tiền.`} />}</li>; })}</ul></section>}
    {user && t.manager_id === user.id && ['pending','rejected'].includes(t.status) && <Link href={`/giai-dau/tao?edit=${id}`} className="mt-6 inline-flex min-h-11 items-center rounded-control border border-strong px-5 text-sm font-semibold text-pitch">Chỉnh sửa và gửi lại đề xuất →</Link>}
    {manager && user && <TournamentSettlementPanel id={id} userId={user.id} admin={!!admin} />}
    {manager && Date.parse(t.ends_at) > Date.now() && ['pending','published'].includes(t.status) && <section className="mt-8 border-t border-hairline pt-6"><ActionForm payload={{ action: 'cancel', id }} variant="danger" label="Hủy giải đấu" confirmMessage="Hủy giải, trả lịch sân và ghi nhận các khoản cọc cần hoàn?" /></section>}
  </main>;
}
