-- All receivers, invoices, money events, profiles and bookings below roll back.
begin;
insert into auth.users(id) values
 ('c0000000-0000-4000-8000-000000000001'),('c0000000-0000-4000-8000-000000000002'),('c0000000-0000-4000-8000-000000000003');
update profiles set role='owner',owner_application_status='active',payout_bank='MBBank',payout_account='1234567890' where id='c0000000-0000-4000-8000-000000000001';
update profiles set role='admin' where id='c0000000-0000-4000-8000-000000000002';
update booking_operator set owner_id='c0000000-0000-4000-8000-000000000001',bank='MBBank',account_number='1234567890',account_name='TEST ONLY',accepts_new_bookings=true,multi_owner_enabled=false;
update subscription_receiver set connection_id=null,bank='MBBank',account_number='1234567890',account_name='TEST ONLY';
select set_config('request.jwt.claim.sub','c0000000-0000-4000-8000-000000000001',true);
do $$
declare v venues; draft venues; i subscription_invoices; j subscription_invoices; ct uuid; b bookings; result jsonb; until_at timestamptz;
  t timestamptz:=(((now() at time zone 'Asia/Ho_Chi_Minh')::date+1)+time '10:00') at time zone 'Asia/Ho_Chi_Minh';
begin
  assert (get_my_subscription()->>'active')::boolean, 'owners start exempt';
  v:=create_venue('Subscription test','Test address','Test district','0900000000',null,'05:00','23:00','[{"sport":"badminton","court_count":1,"price_per_hour":100000}]');
  draft:=create_venue('Subscription draft','Test address','Test district','0900000000',null,'05:00','23:00','[{"sport":"badminton","court_count":1,"price_per_hour":100000}]');
  update venues set status='active',images='{test1,test2,test3}' where id=v.id;
  select id into ct from courts where venue_id=v.id;
  b:=create_booking(ct,t,t+interval '1 hour','Test','0900000000');
  begin perform create_subscription_invoice(); raise exception 'CHECK_FAILED: exempt invoice';
  exception when raise_exception then if sqlerrm<>'FEE_NOT_REQUIRED' then raise; end if; end;
  begin perform set_owner_subscription_fee(auth.uid(),true); raise exception 'CHECK_FAILED: owner toggles fee';
  exception when raise_exception then if sqlerrm<>'FORBIDDEN' then raise; end if; end;
  perform set_config('request.jwt.claim.sub','c0000000-0000-4000-8000-000000000002',true);
  perform set_owner_subscription_fee('c0000000-0000-4000-8000-000000000001',true);
  assert exists(select 1 from get_admin_subscriptions() where owner_id='c0000000-0000-4000-8000-000000000001' and fee_required and not active), 'admin sees charge status';
  begin perform set_owner_subscription_fee('c0000000-0000-4000-8000-000000000003',true); raise exception 'CHECK_FAILED: player fee';
  exception when raise_exception then if sqlerrm<>'OWNER_NOT_APPROVED' then raise; end if; end;
  perform set_config('request.jwt.claim.sub','c0000000-0000-4000-8000-000000000001',true);
  assert not owner_subscription_allows(auth.uid()), 'unpaid blocks';
  assert not venue_accepts_bookings(v.id), 'public page stops new bookings';
  begin perform create_booking(ct,t+interval '2 hours',t+interval '3 hours','Test','0900000000'); raise exception 'CHECK_FAILED: unpaid booking';
  exception when raise_exception then if sqlerrm<>'VENUE_NOT_ACCEPTING_BOOKINGS' then raise; end if; end;
  begin perform create_venue('Blocked venue','Test address','Test district','0900000000',null,'05:00','23:00','[{"sport":"badminton","court_count":1,"price_per_hour":100000}]'); raise exception 'CHECK_FAILED: unpaid venue';
  exception when raise_exception then if sqlerrm<>'OWNER_SUBSCRIPTION_DUE' then raise; end if; end;
  begin update venues set status='active',images='{test1,test2,test3}' where id=draft.id; raise exception 'CHECK_FAILED: unpaid publishing';
  exception when raise_exception then if sqlerrm<>'OWNER_SUBSCRIPTION_DUE' then raise; end if; end;
  begin insert into courts(venue_id,name,sport) values(v.id,'Blocked','badminton'); raise exception 'CHECK_FAILED: unpaid court';
  exception when raise_exception then if sqlerrm<>'OWNER_SUBSCRIPTION_DUE' then raise; end if; end;
  result:=confirm_payment(b.code,30000,'subscription-old-deposit','{}',null,'MBBank','1234567890');
  assert result->>'reason'='CONFIRMED', 'old deposit is still processed';
  i:=create_subscription_invoice();j:=create_subscription_invoice();assert i.id=j.id and i.amount=299000, 'one pending invoice and server price';
  result:=confirm_subscription_payment(i.code,299000,'fee-wrong','{}',null,'OtherBank','1234567890');assert result->>'reason'='WRONG_RECEIVER';
  result:=confirm_subscription_payment(i.code,299000,'fee-wrong','{}',gen_random_uuid(),'MBBank','1234567890');assert result->>'reason'='WRONG_RECEIVER';
  result:=confirm_subscription_payment(i.code,298999,'fee-short','{}',null,'MBBank','1234567890');assert result->>'reason'='UNDERPAID';
  assert not owner_subscription_allows(auth.uid()), 'underpaid never activates';
  result:=confirm_subscription_payment(i.code,299000,'fee-short','{}',null,'MBBank','1234567890');assert result->>'reason'='ALREADY_PROCESSED';
  assert not owner_subscription_allows(auth.uid()), 'same receipt cannot be increased';
  result:=confirm_subscription_payment(i.code,299000,'fee-full','{}',null,'MBBank','1234567890');assert result->>'reason'='SUBSCRIPTION_PAID';
  select paid_until into until_at from owner_subscriptions where owner_id=auth.uid();
  assert until_at=((now() at time zone 'Asia/Ho_Chi_Minh')+interval '1 month') at time zone 'Asia/Ho_Chi_Minh';
  assert venue_accepts_bookings(v.id), 'paid restores booking';
  result:=confirm_subscription_payment(i.code,299000,'fee-full','{}',null,'MBBank','1234567890');assert result->>'reason'='ALREADY_PROCESSED';
  result:=confirm_subscription_payment(i.code,299000,'fee-duplicate','{}',null,'MBBank','1234567890');assert result->>'reason'='ALREADY_PAID';
  assert (select paid_until=until_at from owner_subscriptions where owner_id=auth.uid()), 'neither retry nor second transfer extends a paid invoice';
  -- Calendar month calculation including leap February; paying early preserves remaining time.
  update owner_subscriptions set paid_until='2096-01-31 10:00:00+07' where owner_id=auth.uid();
  j:=create_subscription_invoice();assert j.id<>i.id;
  result:=confirm_subscription_payment(j.code,299000,'fee-full','{}',null,'MBBank','1234567890');assert result->>'reason'='ALREADY_PROCESSED';
  result:=confirm_subscription_payment(j.code,300000,'fee-early','{}',null,'MBBank','1234567890');assert result->>'reason'='SUBSCRIPTION_PAID';
  assert (select paid_until='2096-02-29 10:00:00+07' from owner_subscriptions where owner_id=auth.uid()), 'calendar month, not 30 days';
  assert (select outcome='overpaid' from subscription_payment_events where transaction_key='mbbank:1234567890:fee-early');
  update owner_subscriptions set paid_until=now() where owner_id=auth.uid();
  assert not owner_subscription_allows(auth.uid()), 'exact expiry blocks without cron';
  perform cancel_booking(b.code);
  assert (select status='cancelled' from bookings where id=b.id), 'expired owner can cancel old booking';
  j:=create_subscription_invoice();
  result:=confirm_subscription_payment(j.code,299000,'fee-late','{}',null,'MBBank','1234567890');assert result->>'reason'='SUBSCRIPTION_PAID';
  assert (select period_start=now() from subscription_invoices where id=j.id), 'late renewal starts when paid';
  update owner_subscriptions set paid_until=now()-interval '1 day' where owner_id=auth.uid();
  perform set_config('request.jwt.claim.sub','c0000000-0000-4000-8000-000000000002',true);
  perform set_owner_subscription_fee('c0000000-0000-4000-8000-000000000001',false);
  assert owner_subscription_allows('c0000000-0000-4000-8000-000000000001'), 'admin exemption restores fee access';
end $$;
select set_config('request.jwt.claim.sub','c0000000-0000-4000-8000-000000000003',true);
set local role authenticated;
do $$ begin
  assert not exists(select 1 from owner_subscriptions), 'other owner cannot read subscriptions';
  assert not exists(select 1 from subscription_invoices), 'other owner cannot read fee invoices';
  assert not exists(select 1 from subscription_payment_events), 'receipts private to admin';
  assert not has_table_privilege('authenticated','owner_subscriptions','UPDATE');
  assert not has_table_privilege('authenticated','subscription_invoices','INSERT');
  assert not has_column_privilege('authenticated','subscription_payment_events','raw','SELECT');
  assert not has_function_privilege('authenticated','confirm_subscription_payment(text,integer,text,jsonb,uuid,text,text)','EXECUTE');
  begin perform get_admin_subscriptions(); raise exception 'CHECK_FAILED: nonadmin list';
  exception when raise_exception then if sqlerrm<>'FORBIDDEN' then raise; end if; end;
end $$;
reset role;
rollback;
